### ISSUE TITLE
[Bug]: In Water seems to break passive sometimes.

### ISSUE THREAD

**Issue by Svastojed** [promcteam/proskillapi#348] opened 2022-07-25 17:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

I ventured into the ocean vanilla and my passive that refreshes every 6 seconds giving me night vision disappeared. now this was warm ocean and i tested same in the other new ocean type. so i am guessing since it works perfectly in made water and old biomes maybe the engine isnt updated to the new biomes for the in water option.

### Expected Behavior

work in all biomes without breaking even new ones.

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

**Comment by lordsrubka5** [comment] 2022-07-25 17:39
Did you perhaps pass through some water logged blocks like kelp?

**Comment by Svastojed** [comment] 2022-07-25 20:51
yes there was kelp there

**Comment by lordsrubka5** [comment] 2022-07-25 20:54
Well I know that there was some issues before with waterlogged blocks nit counting as in water mechanic so check the latest builds or other tickets

**Comment by Travja** [comment] 2022-07-25 21:01
Yeah there should be no distinction by biome. There was some waterlogged issue some time ago but it should be resolved in later builds.

**Comment by Travja** [comment] 2022-07-26 15:29
Could you confirm that you're using one of the later builds of ProSkillAPI and ProMCCore and that the issue is still appearing? Otherwise let's close this ticket.

**Comment by Svastojed** [comment] 2022-08-04 06:12
on latest build it works was that waterlogged issue

**Closed** 2022-08-18 15:12 UTC
Labels: bug, needs info
