### ISSUE TITLE
[Bug] Player Data cannot be loaded and resets if player joins the server during starting up.

### ISSUE THREAD

**Issue by springbreezex** [promcteam/proskillapi#71] opened 2021-09-06 12:45 UTC
The problem happens when players are joining the server during the server starting up.
And this issue is not always reproducible. It does need some luck.

I've tested it in only-spigot and proxy.

For only-spigot, I can't reproduce the issue. Maybe becoz this test server has fewer things to load or the server only allow player join when everything is ready. I'm not sure.

For proxy, I use bungeecord. It HAPPENS usually if I try to join the server immediately after I start the server. It is easy to join the server immediately coz seems like proxy allows players to connect earlier? I'm not sure tho.

But one thing I can confirm is.
Before this start, I've checked players' yml data in the data folder. The two users' data are correctly saved.
But when I joined, the data shown in-game has been reset.

Reference logs and information is in discord ticket #47

**Comment by Travja** [comment] 2021-09-17 04:46
As I'm unable to reproduce this issue and it would ultimately affect very minor amounts of players, I'm going to close this issue. Should anyone face this in the future, it seems that using SQL for data storage resolves this issue, so that is a viable workaround.

**Closed by Travja** 2021-09-17 04:46 UTC
Labels: bug
