### ISSUE TITLE
[Bug]: /GIVE EXP PLAYER COMMANDS DO NOT WORK IN COMMAND BLOCKS 1.16.5 - 1.19

### ISSUE THREAD

**Issue by WerelWolf** [promcteam/proskillapi#410] opened 2022-11-11 18:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

I tested with op and without op, and it doesn't work, it's like the command is not found in the player @p

### Expected Behavior

That you could give xp to the player normally via command blocks, since the custom npc mod uses the command block to give commands via console

### Environment

```markdown
- Server Software: MAGMA or MOHIST servers plugins + mods
Server Software: Paper Spigot 1.17.1
ProSkillAPI Version: 1.1.7.3-ALPHA
ProMCCore Version: 1.0.3.1-ALPHA
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

**Comment by Travja** [comment] 2022-11-15 07:49
I actually just tested this and was unable to reproduce it. I would really recommend updating your plugins since it looks like you're running on some really old versions of the plugins. I'm going to close this, however, until I hear of things not working with newer versions.

**Closed by Travja** 2022-11-15 07:49 UTC
Labels: bug
