### ISSUE TITLE
[Bug]: Skills disappear when having multiple groups

### ISSUE THREAD

**Issue by DrHeretic** [promcteam/proskillapi#357] opened 2022-08-06 07:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

![image](https://user-images.githubusercontent.com/88398845/183239089-ecc9c7f6-6106-4309-9625-b994793a1467.png)

During trying to add extra groups to the listing, it takes away all the skills of the main group and replaces it with just a blank skill menu from the /skill. 

Just having one group "class" being in is fine, adding a second group "crafting" will break the skill list.

It is building the group in the groups.yml.

### Expected Behavior

Being able to see skills when new groups have been added to the profess list.

### Steps To Reproduce

Start off with base group "Class" in one of the class ymls.
Add a new group with a different grouping type.
./class skill
any previous showing skills should be gone.

### Environment

```markdown
- Server Software: Root server 32core
- ProSkillAPI Version: Latest dev build
- ProMCCore Version: Latest dev build
- Plugins: Luckperms, Myworlds, Protocalib
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

### Anything else?

There were no errors with-in console when this is happening.

**Comment by DrHeretic** [comment] 2022-08-06 08:02
When I remove the added groups my skills do come back
![image](https://user-images.githubusercontent.com/88398845/183240356-d4f78e7c-87d2-41ac-8ca1-756bd199f11d.png)

**Comment by DrHeretic** [comment] 2022-08-06 08:04
I did also real quick bring this to a side server with just pro within it. Still was coming up with the same issue.

**Comment by Travja** [comment] 2022-08-18 15:06
I actually have two class groups and don't have this problem. Could you possibly send your associated files so I can see what's going on?

**Comment by Travja** [comment] 2022-11-08 04:49
I'm going to go ahead and close this for now as I'm unable to reproduce it. If more specific information is able to be provided, we can take a closer look at this.

**Closed by Travja** 2022-11-08 04:49 UTC
Labels: bug, needs info
