### ISSUE TITLE
[Enhancement] RayTrace Mechanic

### ISSUE THREAD

**Issue by jpelshani** [promcteam/proskillapi#384] opened 2022-09-15 21:40 UTC
Currently, making a line between two targets or points that has a duration and updates as the targets move is difficult and inaccessible. Making this line also able to target entities, have a particle effect around it, and be as customizable as a particle projectile is very difficult currently, and far too bulky.

A mechanic called 'RayTrace', where you can supply two points, either as offsets of targets or targets themselves, using keys. This line can work as a targetter and whatever specified that touches the line will have child mechanics executed on it. The line should be customizable visually, with you being able to supply all the standard particle options to customize it. It should also update and change as the targets move.

The options for this should be:

- The ability to provide two keys which the line will connect. These keys should be usable on both locations and entities.
- If the line should continue through blocks or stop if a block interrupts the path. 
- This line should have all the standard options for particles.
- A duration.
- The interval that the line will update.
-  What group should be targeted if the line is touched.
-  Icon Key.
-  Max length of line.

Some practical uses of this mechanic would be:

- Creating a visual tether between targets.
- Creating more visually appealing AOE skills, which can move and update with more precision and control.
- Create more interesting projectiles.
- Make a line between targets, with the player not being required to visually look at them.

**Comment by Sentropic** [comment] 2022-10-04 00:21
Duplicate of #369

**Closed by Sentropic** 2022-10-04 00:21 UTC
Labels: enhancement
