### ISSUE TITLE
[Bug]: Player Data loss

### ISSUE THREAD

**Issue by Maxence621** [promcteam/proskillapi#154] opened 2021-11-21 17:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes when one of my player connect in the game, he lose his data ( class, level, skill..)
Even if he take the class again, he start with level 1.

I have a cracked server because some of my player play without Minecraft Premium

### Expected Behavior

I expect that my player don't lose data sometimes (Randomly?) 

### Steps To Reproduce

I don't know the step to reproduce, except connect into the server and lose the data (It happen 4 times only to only 3 players, in 2 week)

### Environment

```markdown
- Server Software: Paper 1.17.1
- ProSkillAPI Version: 1.1.7.3
- ProMCCore Version: 1.0.3.2
- Plugins: AdvancedRegionMarket, AuthMe, BetonQuest, BKCommonLib, ChestShop, Citizens, CommandAPI, CommandPanels, CoreProtect, EffectLib, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, InteractiveChat, ItemJoin, LibsDisguises, LightCleaner, LockettePro, LuckPerms, ModelEngine, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, MythicMobs, NBTAPI, NetheriteGrind, Oh_the_dungeons_youll_go, ore-control, PlaceholderAPI, ProMCCore, ProMCUtilities, ProRPGItems, ProSkillAPI, ProtocolLib, RiseCore, ServersNPC, SilkSpawners, SinglePlayerSleep, SkinsRestorer, TabList, TradeShop, Vault, VoidGen, WanderingTrades, WorldEdit, WorldGuard
```

### latest.log

https://pastebin.com/qpSQEr0q

**Comment by Travja** [comment] 2021-12-14 08:10
This isn't exactly addressed, but more-so logging added and hopefully prevent a full-on loss of data. Please report any further information here.

**Comment by Travja** [comment] 2021-12-22 04:05
Closing for now as the issue is pretty old and not common. If more issues present themselves, we can re-open the issue.

**Closed by Travja** 2021-12-22 04:05 UTC
Labels: bug

**Comment by tangjin0418** [comment] 2023-04-02 17:38
#promcteam/promccore#15
