### ISSUE TITLE
[Bug]: Skills Break on Reload

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#315] opened 2022-06-01 01:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Sometimes when reloading the plugin, some skills, or less often classes, run into an error and causes it to break. The "break" can be either ot turning into default empty one, setting the cost to 0 and maxing it out or being fully gone from gui. 

This only happens after reloading the plugin, didnt have that many tests to see if closing and starting the server is the same. This is not a good combination with the previous bug report.

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

### latest.log

Can be found on discord, cant copy paste on phone sorry.

**Comment by Travja** [comment] 2022-07-08 16:24
As we've determined that this is likely caused by a bad combination of TAB and placeholders, I'm going to close this. I may address these issues later on and add some security in the way that placeholders are used.

**Closed by Travja** 2022-07-08 16:24 UTC
Labels: bug, low-priority, needs info
