### ISSUE TITLE
[Bug] Damage ignoring PVP Protection

### ISSUE THREAD

**Issue by springbreezex** [promcteam/proskillapi#72] opened 2021-09-06 12:46 UTC
Damage mechanic under projectile with knockback false can ignore any damage protection plugin (WorldGuard pvp deny etc). Meanwhile, no-knockback damage under targeter like area will not have the issue. And here are the skills producing the bug.

Sample test skills are sent in discord ticket #47.

**Comment by Travja** [comment] 2021-09-17 04:02
This bug should be addressed in the latest dev build. Closing this for now. If the issue is still present, we will reopen this.

**Closed by Travja** 2021-09-17 04:02 UTC
Labels: bug
