### ISSUE TITLE
[Bug]: error health with MMOitems

### ISSUE THREAD

**Issue by ronyan149** [promcteam/proskillapi#504] opened 2023-07-31 07:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

I am using MMOItems to create armour which when worn increase HP so like if armour gives 500hp your base hp is 20 and leveling up to level 10 gives u 200hp then yo will have 720hp in total, I have disabled "force-scaling" in GUI section and enabled "modify-health"  in Class section in config.yml but whenever the item in hand changes the HP of player drops back to 220HP like the HP added by MMOItems resets to 0, but when I disable "modify-health" in Class section, this issue gets fixed but the base proskillapi doesn't add any HP for example the 200HP  for being level 10, is there any way I can fix this? Please help me 

### Environment

```markdown
- Server Software:1.19.2
- ProSkillAPI Version:1.1.9-R0.2
- ProMCCore Version:1.0.4-R0.13
- Plugins:LuckPerms, PlaceholderAPI, ProtocolLib, LibsDisguises, BetterPrefix, Zenchantments, Geyser-Spigot, Vault, WorldEdit, Essentials, WorldGuard, Multiverse-Core, MythicMobs, DeluxeMenus, LeaderMobs, NexEngine, EssentialsSpawn, MythicLib, AuthMe, ProMCCore, ProSkillAPI (SkillAPI), LWC, HoloMobHealth, PlayerPoints, SilkSpawners, RaidsPerRegion, ExcellentCrates, TAB, MMOItems
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

**Comment by Travja** [comment] 2023-07-31 07:18
Duplicate of #473

**Closed** 2023-07-31 07:18 UTC
Labels: bug

**Comment by Travja** [comment] 2023-08-24 04:56
@ronyan149 I might open this ticket and close the other one if you can provide some minimum reproducible set up since it appears that the other ticket author is not responsive on Github.
