### ISSUE TITLE
[Bug]: Unable to work after overloading

### ISSUE THREAD

**Issue by TomGiHub** [promcteam/proskillapi#397] opened 2022-10-22 03:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

1. After the plug-in configuration is modified for the first time, use/class reload or restart the server, and it will run normally. However, if you use/class reload again or restart the server, it will report an error and some functions will not work normally.

2. As long as the plug-in configuration is not modified,/class reload is used, or the server is restarted, it always runs normally without error

https://pastebin.com/5KGeguKr

### Expected Behavior

After I modify the content, the plug-in can run normally after reloading

### Environment

```markdown
- Server Software: Spigot-1.19.2
- ProSkillAPI Version: ProSkillAPI v1.1.7.17-4252334
- ProMCCore Version: ProMCCore v1.0.3.9-3421730
- Plugins:
beautyquests-0.19.7.jar
Citizens-2.0.30-b2712.jar
HolographicDisplays-3.0.0-SNAPSHOT.jar
KingdomsX-1.14.15.1.jar
LuckPerms5.4.4.9.jar
Multiverse-Core-4.3.1.jar
MythicMobs-5.1.4.jar
ProtocolLib.jar
prorpgitems-1.0.3.16-4151939.jar
promccore-1.0.3.9-3421730.jar
PlaceholderAPI-2.11.2.jar
proskillapi-1.1.7.17-4252334.jar
Vault.jar
ServerBuild-V0.0.1(2).jar
StarLauncher_verification_Bukkit (#D-5.0.0.1).jar
worldedit-bukkit-7.2.12.jar
SkinsRestorer.jar
Shopkeepers-2.16.2.jar
LiveGet-V0.0.2-fix(fix).jar
VoidGen-2.2.1.jar
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

**Comment by Travja** [comment] 2022-10-29 03:01
Are you seeing this behavior consistently or only sometimes? That error makes me think that it's saving partial/incomplete data or that it's saving empty files altogether. This shouldn't happen--at least not frequently.

**Comment by TomGiHub** [comment] 2022-10-31 08:19
It always appears.When I add a class/skill and reload it for the second time, an error will appear

**Comment by Travja** [comment] 2022-11-02 04:25
I actually can't reproduce this. I've tried adding/removing both skills and classes and I've reloaded numerous times. I'm not entirely sure what's going on.

**Comment by Travja** [comment] 2022-11-02 05:02
I just pushed some new code that might impact this slightly. Honestly I don't see it fixing your issue, but you could give it a shot. The error itself seems to relate more the `groups.yml` file. Could you share that with me or try regenerating it and see if things work properly?

**Comment by TomGiHub** [comment] 2022-11-02 10:32
It may be a file problem. I used the wrong file https://promcteam.github.io/proskillapi/ Created. I tested that there was no problem with the plug-in generation and some files provided by others

**Comment by Travja** [comment] 2022-11-02 13:05
So we're good to close this then?

**Comment by TomGiHub** [comment] 2022-11-03 00:22
Yes, of course

**Closed** 2022-11-03 00:22 UTC
Labels: bug
