### ISSUE TITLE
[Bug]: cooldown mechanic doesn't work

### ISSUE THREAD

**Issue by k437u** [promcteam/proskillapi#305] opened 2022-05-16 19:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

the "cooldown" mechanic should supposedly increase cooldown of a skill but doesn't

### Expected Behavior

i should increase cooldown

### Steps To Reproduce

1. create a skill
2. specify any trigger
3. then specify mechanic the same way as any other mechanic
4. specify mechanic settings(tried leaving the field "skill" as "all" and specifying the skill too)
5. save, upload, reload
6. sadge

### Environment

```markdown
- Server Software: paper 1.17.1
promccore and proskillapi latest version available on spigot
```

### Anything else?

sorry actually i didn't test it with OP tbh
tho i don't think it would affect this

**Comment by Travja** [comment] 2022-06-17 05:10
So I just tested this out. Looks like the CooldownMechanic works as intended for _other_ skills, just not the skill that's casting the mechanic. This is because the cooldown is only started for the current skill **after** the child mechanics/conditions/etc are fired off.

Now, I might be able to adjust this and make it so it effectively adds to the effective cooldown... however, if you're intending to modify the current skill's cooldown on cast, why not just adjust the skill's actual cooldown? I'm hesitant to actually feel like this is needed at present because I feel like this mechanic is intended more as a means of decreasing skill cooldowns for other active skills.

If anyone else feels that this should be updated, please let me know. I'll close this in a couple of days if I don't hear anything back about this.

**Comment by k437u** [comment] 2022-06-17 05:35
I needed to modify the skill cooldown if it was successful so it can't be done anyhow unless using this mechanic.

If you make the mechanic be able to modify the cast skill cooldown i don't think it's any of a problem because you can directly specify what skill is affected

**Comment by Travja** [comment] 2022-06-17 05:38
Fair enough. The other thing you could try is doing a delay mechanic with the cooldown attached

**Closed** 2022-06-18 21:40 UTC
Labels: bug
